import fs from 'node:fs';
import path from 'node:path';
import { memoryExists } from '../core/io.js';
import { loadState } from '../core/state.js';
import { loadConfig } from '../core/config.js';
import { resolveInstructions, loadInstructions } from '../core/instructions.js';
import { logger } from '../core/logger.js';

export interface ExportOptions {
  format: 'copilot-instructions' | 'cursor-rules' | 'agents-md' | 'claude-system';
  output?: string;
  project?: string;
  agent?: string;
}

export function runExport(options: ExportOptions): void {
  if (!memoryExists()) {
    console.error('Error: .brainclaw/ not found. Run `brainclaw init` first.');
    process.exit(1);
  }

  const content = generateExport(options);

  if (options.output) {
    const dir = path.dirname(options.output);
    if (dir && !fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(options.output, content, 'utf-8');
    console.log(`✔ Exported to ${options.output}`);
  } else {
    console.log(content);
  }
}

function generateExport(options: ExportOptions): string {
  switch (options.format) {
    case 'copilot-instructions':
      return generateCopilotInstructions(options);
    case 'cursor-rules':
      return generateCursorRules(options);
    case 'agents-md':
      return generateAgentsMd(options);
    case 'claude-system':
      return generateClaudeSystem(options);
    default:
      throw new Error(`Unknown export format: ${options.format}`);
  }
}

function getInstructionText(options: ExportOptions): string[] {
  try {
    const all = loadInstructions();
    const resolved = resolveInstructions(all, {
      project: options.project,
      agent: options.agent,
    });
    return resolved.filter(i => i.active).map(i => i.text);
  } catch (err) {
    logger.debug('Failed to resolve instructions for export:', err);
    return [];
  }
}

function getConstraintsSummary(): string {
  try {
    const state = loadState();
    const active = state.active_constraints.filter(c => c.status === 'active');
    if (active.length === 0) return '';
    return '## Active Constraints\n\n' + active.map(c => `- ${c.text}`).join('\n');
  } catch (err) {
    logger.debug('Failed to load constraints for export:', err);
    return '';
  }
}

function getDecisionsSummary(): string {
  try {
    const state = loadState();
    if (state.recent_decisions.length === 0) return '';
    return '## Key Decisions\n\n' + state.recent_decisions.slice(-10).map(d => `- ${d.text}`).join('\n');
  } catch {
    return '';
  }
}

function getTrapsSummary(): string {
  try {
    const state = loadState();
    const traps = state.known_traps.filter(t => t.visibility === 'shared');
    if (traps.length === 0) return '';
    return '## Known Traps\n\n' + traps.map(t => `- [${t.severity}] ${t.text}`).join('\n');
  } catch {
    return '';
  }
}

function generateCopilotInstructions(options: ExportOptions): string {
  const config = loadConfig();
  const lines: string[] = [
    `# Copilot Instructions — ${config.project_name}`,
    '',
    '> Generated by brainclaw. Do not edit manually — run `brainclaw export --format copilot-instructions` to regenerate.',
    '',
  ];

  const instructions = getInstructionText(options);
  if (instructions.length > 0) {
    lines.push('## Instructions\n');
    for (const inst of instructions) lines.push(`- ${inst}`);
    lines.push('');
  }

  const constraints = getConstraintsSummary();
  if (constraints) { lines.push(constraints); lines.push(''); }

  const decisions = getDecisionsSummary();
  if (decisions) { lines.push(decisions); lines.push(''); }

  const traps = getTrapsSummary();
  if (traps) { lines.push(traps); lines.push(''); }

  return lines.join('\n');
}

function generateCursorRules(options: ExportOptions): string {
  const instructions = getInstructionText(options);
  const state = loadState();
  const lines: string[] = ['# .cursorrules — generated by brainclaw', ''];

  if (instructions.length > 0) {
    lines.push('## Instructions');
    for (const inst of instructions) lines.push(`- ${inst}`);
    lines.push('');
  }

  const constraints = state.active_constraints.filter(c => c.status === 'active');
  if (constraints.length > 0) {
    lines.push('## Constraints');
    for (const c of constraints) lines.push(`- ${c.text}`);
    lines.push('');
  }

  return lines.join('\n');
}

function generateAgentsMd(options: ExportOptions): string {
  const config = loadConfig();
  const instructions = getInstructionText(options);
  const state = loadState();
  const lines: string[] = [
    `# AGENTS.md — ${config.project_name}`,
    '',
    '> Generated by brainclaw.',
    '',
    '## Project Instructions',
    '',
  ];

  if (instructions.length > 0) {
    for (const inst of instructions) lines.push(`- ${inst}`);
  } else {
    lines.push('_No project instructions defined._');
  }
  lines.push('');

  const activePlans = state.plan_items.filter(p => p.status === 'todo' || p.status === 'in_progress');
  if (activePlans.length > 0) {
    lines.push('## Active Plan Items\n');
    for (const p of activePlans.slice(0, 10)) {
      lines.push(`- [${p.status}] ${p.text}${p.assignee ? ` (@${p.assignee})` : ''}`);
    }
    lines.push('');
  }

  const traps = state.known_traps.filter(t => t.visibility === 'shared');
  if (traps.length > 0) {
    lines.push('## Known Traps\n');
    for (const t of traps.slice(0, 10)) {
      lines.push(`- [${t.severity}] ${t.text}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

function generateClaudeSystem(options: ExportOptions): string {
  const instructions = getInstructionText(options);
  const state = loadState();
  const config = loadConfig();

  const parts: string[] = [`You are working on ${config.project_name}.`];

  if (instructions.length > 0) {
    parts.push('\n\nProject instructions:\n' + instructions.map(i => `- ${i}`).join('\n'));
  }

  const constraints = state.active_constraints.filter(c => c.status === 'active');
  if (constraints.length > 0) {
    parts.push('\n\nActive constraints:\n' + constraints.map(c => `- ${c.text}`).join('\n'));
  }

  const traps = state.known_traps.filter(t => t.visibility === 'shared');
  if (traps.length > 0) {
    parts.push('\n\nKnown traps to avoid:\n' + traps.map(t => `- [${t.severity}] ${t.text}`).join('\n'));
  }

  return parts.join('');
}
