import fs from 'node:fs';
import path from 'node:path';
import { memoryExists } from '../core/io.js';

export interface InstallHooksOptions {
  force?: boolean;
}

export function runInstallHooks(options: InstallHooksOptions = {}): void {
  if (!memoryExists()) {
    console.error('Error: .brainclaw/ not found. Run `brainclaw init` first.');
    process.exit(1);
  }

  const gitRoot = findGitRoot(process.cwd());
  if (!gitRoot) {
    console.error('Error: no .git/ directory found. Is this a Git repository?');
    process.exit(1);
  }

  const hooksDir = path.join(gitRoot, '.git', 'hooks');
  if (!fs.existsSync(hooksDir)) {
    fs.mkdirSync(hooksDir, { recursive: true });
  }

  const hookPath = path.join(hooksDir, 'pre-commit');
  if (fs.existsSync(hookPath) && !options.force) {
    console.error(`Error: pre-commit hook already exists at ${hookPath}`);
    console.error('Use --force to overwrite.');
    process.exit(1);
  }

  fs.writeFileSync(hookPath, generateHookScript(), { encoding: 'utf-8', mode: 0o755 });
  console.log(`✔ pre-commit hook installed at ${hookPath}`);
  console.log('  Checks: sensitive content in .brainclaw/ + active constraint violations.');
  console.log('  To bypass (not recommended): git commit --no-verify');

  const postMergePath = path.join(hooksDir, 'post-merge');
  if (!fs.existsSync(postMergePath) || options.force) {
    fs.writeFileSync(postMergePath, generatePostMergeScript(), { encoding: 'utf-8', mode: 0o755 });
    console.log(`✔ post-merge hook installed at ${postMergePath}`);
    console.log('  Auto-releases claims whose scope was touched by the merge.');
  }
}

function generatePostMergeScript(): string {
  return `#!/bin/sh
# brainclaw post-merge hook
# Auto-releases claims whose scope overlaps with files changed by the merge
# Generated by: brainclaw install-hooks

BCLAW_CMD=""
if command -v brainclaw >/dev/null 2>&1; then
  BCLAW_CMD="brainclaw"
elif command -v bclaw >/dev/null 2>&1; then
  BCLAW_CMD="bclaw"
else
  BCLAW_CMD="npx --no brainclaw"
fi

$BCLAW_CMD release-claims --from-git-diff 2>/dev/null || true
`;
}

function findGitRoot(cwd: string): string | undefined {
  let dir = cwd;
  while (true) {
    if (fs.existsSync(path.join(dir, '.git'))) return dir;
    const parent = path.dirname(dir);
    if (parent === dir) return undefined;
    dir = parent;
  }
}

function generateHookScript(): string {
  // Use node directly to avoid sh.exe pipe issues on Windows (SIGPIPE).
  // The script is a self-contained node -e that runs both checks.
  return `#!/bin/sh
# brainclaw pre-commit hook — generated by brainclaw install-hooks
# Runs via node to avoid sh.exe SIGPIPE issues on Windows.
exec node -e "
const { execSync } = require('child_process');
const staged = execSync('git diff --cached --name-only', { encoding: 'utf-8' }).trim();
if (!staged) process.exit(0);

// Check 1: reject staged .brainclaw/ files
const brainclawFiles = staged.split('\\\\n').filter(f => f.startsWith('.brainclaw/'));
if (brainclawFiles.length > 0) {
  process.stderr.write('\\\\nbrainclaw: .brainclaw/ files are staged — blocked.\\\\n');
  brainclawFiles.forEach(f => process.stderr.write('  ' + f + '\\\\n'));
  process.stderr.write('  Fix: git reset HEAD .brainclaw/\\\\n\\\\n');
  process.exit(1);
}

// Check 2: active constraint violations
try {
  execSync('brainclaw check-constraints --staged', { stdio: 'inherit' });
} catch (e) {
  if (e.status) process.exit(e.status);
}
" 2>&1 || exit $?
`;
}
