import fs from 'node:fs';
import path from 'node:path';
import { memoryExists } from '../core/io.js';

export interface InstallHooksOptions {
  force?: boolean;
}

export function runInstallHooks(options: InstallHooksOptions = {}): void {
  if (!memoryExists()) {
    console.error('Error: .brainclaw/ not found. Run `brainclaw init` first.');
    process.exit(1);
  }

  const gitRoot = findGitRoot(process.cwd());
  if (!gitRoot) {
    console.error('Error: no .git/ directory found. Is this a Git repository?');
    process.exit(1);
  }

  const hooksDir = path.join(gitRoot, '.git', 'hooks');
  if (!fs.existsSync(hooksDir)) {
    fs.mkdirSync(hooksDir, { recursive: true });
  }

  const hookPath = path.join(hooksDir, 'pre-commit');
  if (fs.existsSync(hookPath) && !options.force) {
    console.error(`Error: pre-commit hook already exists at ${hookPath}`);
    console.error('Use --force to overwrite.');
    process.exit(1);
  }

  fs.writeFileSync(hookPath, generateHookScript(), { encoding: 'utf-8', mode: 0o755 });
  console.log(`✔ pre-commit hook installed at ${hookPath}`);
  console.log('  Checks: sensitive content in .brainclaw/ + active constraint violations.');
  console.log('  To bypass (not recommended): git commit --no-verify');

  const postMergePath = path.join(hooksDir, 'post-merge');
  if (!fs.existsSync(postMergePath) || options.force) {
    fs.writeFileSync(postMergePath, generatePostMergeScript(), { encoding: 'utf-8', mode: 0o755 });
    console.log(`✔ post-merge hook installed at ${postMergePath}`);
    console.log('  Auto-releases claims whose scope was touched by the merge.');
  }

  // Claude Code preToolUse hook
  const claudeHookPath = path.join(hooksDir, 'claude-pre-tool.sh');
  if (!fs.existsSync(claudeHookPath) || options.force) {
    fs.writeFileSync(claudeHookPath, generateClaudePreToolScript(), { encoding: 'utf-8', mode: 0o755 });
    console.log(`✔ Claude Code preToolUse hook generated at ${claudeHookPath}`);

    // Update claude.json if present
    const claudeJsonPath = path.join(gitRoot, 'claude.json');
    let claudeJson: any = {};
    if (fs.existsSync(claudeJsonPath)) {
      try {
        claudeJson = JSON.parse(fs.readFileSync(claudeJsonPath, 'utf8'));
      } catch (e) {}
    }
    if (!claudeJson.hooks) claudeJson.hooks = {};
    claudeJson.hooks.preToolUse = '.git/hooks/claude-pre-tool.sh';
    fs.writeFileSync(claudeJsonPath, JSON.stringify(claudeJson, null, 2), 'utf8');
    console.log('  ✔ claude.json updated to use preToolUse hook.');
  }
}

function generateClaudePreToolScript(): string {
  return `#!/bin/sh
# brainclaw Claude Code preToolUse hook
# Generated by: brainclaw install-hooks
exec node -e "
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const toolName = process.env.CLAUDE_TOOL_NAME || process.argv[2] || process.env.TOOL_NAME || '';
const isWrite = /edit|write|replace|bash|str_replace/i.test(toolName);

if (!isWrite || !toolName) process.exit(0);

try {
  const BCLAW_CMD = fs.existsSync(path.join(process.cwd(), 'node_modules', '.bin', 'brainclaw')) 
    ? 'npx brainclaw' : 'brainclaw';
  const out = execSync(BCLAW_CMD + ' claim list --json', { encoding: 'utf8', stdio: ['pipe', 'pipe', 'ignore'] });
  const claims = JSON.parse(out);
  if (claims && claims.length > 0) process.exit(0);
} catch (e) {
  // ignore if brainclaw not found or fails
  process.exit(0);
}

const sessionMark = path.join(process.cwd(), '.brainclaw', 'tmp', 'claude_warned');
if (!fs.existsSync(path.dirname(sessionMark))) fs.mkdirSync(path.dirname(sessionMark), { recursive: true });

if (fs.existsSync(sessionMark)) {
  const mtime = fs.statSync(sessionMark).mtimeMs;
  if (Date.now() - mtime < 2 * 60 * 60 * 1000) {
    process.exit(0); // already warned this session
  }
}
fs.writeFileSync(sessionMark, Date.now().toString());

process.stderr.write('\\n[Brainclaw] ⚠️  WARNING: You are about to use an Edit/Write tool (' + toolName + ') but you have NO active claim.\\n');
process.stderr.write('[Brainclaw] Consider running \\\`brainclaw claim create <scope>\\\` to lock your work and avoid conflicts.\\n\\n');
" 2>&1 || exit 0
`;
}

function generatePostMergeScript(): string {
  return `#!/bin/sh
# brainclaw post-merge hook
# Auto-releases claims whose scope overlaps with files changed by the merge
# Generated by: brainclaw install-hooks

BCLAW_CMD=""
if command -v brainclaw >/dev/null 2>&1; then
  BCLAW_CMD="brainclaw"
elif command -v bclaw >/dev/null 2>&1; then
  BCLAW_CMD="bclaw"
else
  BCLAW_CMD="npx --no brainclaw"
fi

$BCLAW_CMD release-claims --from-git-diff 2>/dev/null || true
`;
}

function findGitRoot(cwd: string): string | undefined {
  let dir = cwd;
  while (true) {
    if (fs.existsSync(path.join(dir, '.git'))) return dir;
    const parent = path.dirname(dir);
    if (parent === dir) return undefined;
    dir = parent;
  }
}

function generateHookScript(): string {
  // Use node directly to avoid sh.exe pipe issues on Windows (SIGPIPE).
  // The script is a self-contained node -e that runs both checks.
  return `#!/bin/sh
# brainclaw pre-commit hook — generated by brainclaw install-hooks
# Runs via node to avoid sh.exe SIGPIPE issues on Windows.
exec node -e "
const { execSync } = require('child_process');
const staged = execSync('git diff --cached --name-only', { encoding: 'utf-8' }).trim();
if (!staged) process.exit(0);

// Check 1: reject staged .brainclaw/ files
const brainclawFiles = staged.split('\\\\n').filter(f => f.startsWith('.brainclaw/'));
if (brainclawFiles.length > 0) {
  process.stderr.write('\\\\nbrainclaw: .brainclaw/ files are staged — blocked.\\\\n');
  brainclawFiles.forEach(f => process.stderr.write('  ' + f + '\\\\n'));
  process.stderr.write('  Fix: git reset HEAD .brainclaw/\\\\n\\\\n');
  process.exit(1);
}

// Check 2: active constraint violations
try {
  execSync('brainclaw check-constraints --staged', { stdio: 'inherit' });
} catch (e) {
  if (e.status) process.exit(e.status);
}
" 2>&1 || exit $?
`;
}
