// AUTO-GENERATED by scripts/build-mcp-schemas.mjs — DO NOT EDIT BY HAND.
// Source zod schemas: src/core/loops/types.ts, src/core/loops/facade-schema.ts
// Regenerate: npm run build:mcp-schemas
//
// This file materializes the zod-derived JSON Schema view consumed by the
// MCP tool catalog (src/commands/mcp.ts). Drift between the committed
// version of this file and a fresh regen is caught at CI time by
// tests/unit/mcp-zod-parity.test.ts (pln#494 phase 2).

export const generatedSchemas = {
  "LoopPhase": {
    "type": "object",
    "properties": {
      "name": {
        "type": "string",
        "minLength": 1
      },
      "advance_when": {
        "type": "string",
        "enum": [
          "all",
          "any"
        ]
      }
    },
    "required": [
      "name"
    ],
    "additionalProperties": false
  },
  "LoopSlotInput": {
    "type": "object",
    "properties": {
      "slot_id": {
        "type": "string",
        "pattern": "^lsl_[0-9a-z]+$"
      },
      "role": {
        "type": "string",
        "minLength": 1
      },
      "agent": {
        "type": "string"
      },
      "agent_id": {
        "type": "string"
      },
      "assignment_id": {
        "type": "string"
      },
      "claim_id": {
        "type": "string"
      },
      "phase": {
        "type": "string"
      },
      "status": {
        "type": "string",
        "enum": [
          "open",
          "assigned",
          "working",
          "done",
          "failed",
          "cancelled"
        ]
      }
    },
    "required": [
      "role"
    ],
    "additionalProperties": false
  }
} as const;
