// AUTO-GENERATED by scripts/build-mcp-schemas.mjs — DO NOT EDIT BY HAND.
// Source zod schemas: src/core/loops/types.ts, src/core/loops/facade-schema.ts
// Regenerate: npm run build:mcp-schemas
//
// This file materializes the zod-derived JSON Schema view consumed by the
// MCP tool catalog (src/commands/mcp.ts). Drift between the committed
// version of this file and a fresh regen is caught at CI time by
// tests/unit/mcp-zod-parity.test.ts (pln#494 phase 2).

export const generatedSchemas = {
  "LoopPhase": {
    "type": "object",
    "properties": {
      "name": {
        "type": "string",
        "minLength": 1
      },
      "advance_when": {
        "type": "string",
        "enum": [
          "all",
          "any"
        ]
      },
      "context_filter": {
        "minItems": 1,
        "type": "array",
        "items": {
          "type": "string",
          "enum": [
            "traps",
            "feedback",
            "runtime_notes",
            "decisions",
            "constraints",
            "handoffs",
            "plans",
            "candidates",
            "project_vision",
            "critique_history",
            "revision_history",
            "synthesis_artifact",
            "*"
          ]
        }
      },
      "advance_gate": {
        "$ref": "#/$defs/__schema0"
      }
    },
    "required": [
      "name"
    ],
    "additionalProperties": false,
    "$defs": {
      "__schema0": {
        "anyOf": [
          {
            "oneOf": [
              {
                "type": "object",
                "properties": {
                  "kind": {
                    "type": "string",
                    "const": "phase_reached"
                  },
                  "phase": {
                    "type": "string",
                    "minLength": 1
                  }
                },
                "required": [
                  "kind",
                  "phase"
                ],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "kind": {
                    "type": "string",
                    "const": "reviewer_green"
                  }
                },
                "required": [
                  "kind"
                ],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "kind": {
                    "type": "string",
                    "const": "max_iterations"
                  },
                  "n": {
                    "type": "integer",
                    "exclusiveMinimum": 0,
                    "maximum": 9007199254740991
                  }
                },
                "required": [
                  "kind",
                  "n"
                ],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "kind": {
                    "type": "string",
                    "const": "min_iterations"
                  },
                  "n": {
                    "type": "integer",
                    "exclusiveMinimum": 0,
                    "maximum": 9007199254740991
                  }
                },
                "required": [
                  "kind",
                  "n"
                ],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "kind": {
                    "type": "string",
                    "const": "artifact_produced"
                  },
                  "phase": {
                    "type": "string",
                    "minLength": 1
                  },
                  "type": {
                    "type": "string",
                    "minLength": 1
                  }
                },
                "required": [
                  "kind",
                  "phase",
                  "type"
                ],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "kind": {
                    "type": "string",
                    "const": "min_artifacts_by_type"
                  },
                  "type": {
                    "type": "string",
                    "minLength": 1
                  },
                  "n": {
                    "type": "integer",
                    "exclusiveMinimum": 0,
                    "maximum": 9007199254740991
                  },
                  "scope": {
                    "type": "string",
                    "enum": [
                      "phase",
                      "loop"
                    ]
                  }
                },
                "required": [
                  "kind",
                  "type",
                  "n",
                  "scope"
                ],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "kind": {
                    "type": "string",
                    "const": "no_open_questions"
                  }
                },
                "required": [
                  "kind"
                ],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "kind": {
                    "type": "string",
                    "const": "manual"
                  }
                },
                "required": [
                  "kind"
                ],
                "additionalProperties": false
              }
            ]
          },
          {
            "type": "object",
            "properties": {
              "kind": {
                "type": "string",
                "const": "any"
              },
              "conditions": {
                "minItems": 1,
                "type": "array",
                "items": {
                  "$ref": "#/$defs/__schema0"
                }
              }
            },
            "required": [
              "kind",
              "conditions"
            ],
            "additionalProperties": false
          },
          {
            "type": "object",
            "properties": {
              "kind": {
                "type": "string",
                "const": "all"
              },
              "conditions": {
                "minItems": 1,
                "type": "array",
                "items": {
                  "$ref": "#/$defs/__schema0"
                }
              }
            },
            "required": [
              "kind",
              "conditions"
            ],
            "additionalProperties": false
          }
        ]
      }
    }
  },
  "LoopSlotInput": {
    "type": "object",
    "properties": {
      "slot_id": {
        "type": "string",
        "pattern": "^lsl_[0-9a-z]+$"
      },
      "role": {
        "type": "string",
        "minLength": 1
      },
      "agent": {
        "type": "string"
      },
      "agent_id": {
        "type": "string"
      },
      "assignment_id": {
        "type": "string"
      },
      "claim_id": {
        "type": "string"
      },
      "phase": {
        "type": "string"
      },
      "status": {
        "type": "string",
        "enum": [
          "open",
          "assigned",
          "working",
          "waiting_input",
          "done",
          "failed",
          "cancelled"
        ]
      },
      "current_turn_id": {
        "type": "string"
      }
    },
    "required": [
      "role"
    ],
    "additionalProperties": false
  }
} as const;
