// AUTO-GENERATED by scripts/build-mcp-schemas.mjs — DO NOT EDIT BY HAND.
// Source zod schemas: src/core/loops/types.ts, src/core/loops/facade-schema.ts,
// src/core/capture-schema.ts, src/core/sequence-request-schema.ts,
// src/core/claim-request-schema.ts, src/core/session-request-schema.ts,
// src/core/step-request-schema.ts
// Regenerate: npm run build:mcp-schemas
//
// This file materializes the zod-derived JSON Schema view consumed by the
// MCP tool catalog (src/commands/mcp.ts). Drift between the committed
// version of this file and a fresh regen is caught at CI time by
// tests/unit/mcp-zod-parity.test.ts (pln#494 phase 2).

export const generatedSchemas = {
  "LoopPhase": {
    "type": "object",
    "properties": {
      "name": {
        "type": "string",
        "minLength": 1
      },
      "advance_when": {
        "type": "string",
        "enum": [
          "all",
          "any"
        ]
      },
      "context_filter": {
        "minItems": 1,
        "type": "array",
        "items": {
          "type": "string",
          "enum": [
            "traps",
            "feedback",
            "runtime_notes",
            "decisions",
            "constraints",
            "handoffs",
            "plans",
            "candidates",
            "project_vision",
            "critique_history",
            "revision_history",
            "synthesis_artifact",
            "*"
          ]
        }
      },
      "advance_gate": {
        "$ref": "#/$defs/__schema0"
      }
    },
    "required": [
      "name"
    ],
    "additionalProperties": false,
    "$defs": {
      "__schema0": {
        "anyOf": [
          {
            "oneOf": [
              {
                "type": "object",
                "properties": {
                  "kind": {
                    "type": "string",
                    "const": "phase_reached"
                  },
                  "phase": {
                    "type": "string",
                    "minLength": 1
                  }
                },
                "required": [
                  "kind",
                  "phase"
                ],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "kind": {
                    "type": "string",
                    "const": "reviewer_green"
                  }
                },
                "required": [
                  "kind"
                ],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "kind": {
                    "type": "string",
                    "const": "max_iterations"
                  },
                  "n": {
                    "type": "integer",
                    "exclusiveMinimum": 0,
                    "maximum": 9007199254740991
                  }
                },
                "required": [
                  "kind",
                  "n"
                ],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "kind": {
                    "type": "string",
                    "const": "min_iterations"
                  },
                  "n": {
                    "type": "integer",
                    "exclusiveMinimum": 0,
                    "maximum": 9007199254740991
                  }
                },
                "required": [
                  "kind",
                  "n"
                ],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "kind": {
                    "type": "string",
                    "const": "artifact_produced"
                  },
                  "phase": {
                    "type": "string",
                    "minLength": 1
                  },
                  "type": {
                    "type": "string",
                    "minLength": 1
                  }
                },
                "required": [
                  "kind",
                  "phase",
                  "type"
                ],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "kind": {
                    "type": "string",
                    "const": "min_artifacts_by_type"
                  },
                  "type": {
                    "type": "string",
                    "minLength": 1
                  },
                  "n": {
                    "type": "integer",
                    "exclusiveMinimum": 0,
                    "maximum": 9007199254740991
                  },
                  "scope": {
                    "type": "string",
                    "enum": [
                      "phase",
                      "loop"
                    ]
                  }
                },
                "required": [
                  "kind",
                  "type",
                  "n",
                  "scope"
                ],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "kind": {
                    "type": "string",
                    "const": "no_open_questions"
                  }
                },
                "required": [
                  "kind"
                ],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "kind": {
                    "type": "string",
                    "const": "manual"
                  }
                },
                "required": [
                  "kind"
                ],
                "additionalProperties": false
              }
            ]
          },
          {
            "type": "object",
            "properties": {
              "kind": {
                "type": "string",
                "const": "any"
              },
              "conditions": {
                "minItems": 1,
                "type": "array",
                "items": {
                  "$ref": "#/$defs/__schema0"
                }
              }
            },
            "required": [
              "kind",
              "conditions"
            ],
            "additionalProperties": false
          },
          {
            "type": "object",
            "properties": {
              "kind": {
                "type": "string",
                "const": "all"
              },
              "conditions": {
                "minItems": 1,
                "type": "array",
                "items": {
                  "$ref": "#/$defs/__schema0"
                }
              }
            },
            "required": [
              "kind",
              "conditions"
            ],
            "additionalProperties": false
          }
        ]
      }
    }
  },
  "LoopSlotInput": {
    "type": "object",
    "properties": {
      "slot_id": {
        "type": "string",
        "pattern": "^lsl_[0-9a-z]+$"
      },
      "role": {
        "type": "string",
        "minLength": 1
      },
      "agent": {
        "type": "string"
      },
      "agent_id": {
        "type": "string"
      },
      "assignment_id": {
        "type": "string"
      },
      "claim_id": {
        "type": "string"
      },
      "phase": {
        "type": "string"
      },
      "status": {
        "type": "string",
        "enum": [
          "open",
          "assigned",
          "working",
          "waiting_input",
          "done",
          "failed",
          "cancelled"
        ]
      },
      "current_turn_id": {
        "type": "string"
      }
    },
    "required": [
      "role"
    ],
    "additionalProperties": false
  },
  "WriteNoteRequest": {
    "type": "object",
    "properties": {
      "text": {
        "type": "string",
        "description": "Note content."
      },
      "agent": {
        "type": "string",
        "description": "Agent name."
      },
      "agentId": {
        "type": "string",
        "description": "Registered agent id."
      },
      "tags": {
        "type": "array",
        "items": {
          "type": "string"
        },
        "description": "Optional tags."
      },
      "visibility": {
        "type": "string",
        "description": "Visibility: shared, machine, private."
      },
      "ttl": {
        "type": "string",
        "description": "Optional TTL: 30m, 2h, 7d."
      },
      "autoReflect": {
        "type": "boolean",
        "description": "Attempt to reflect the runtime note into durable memory immediately."
      },
      "crossProject": {
        "type": "string",
        "description": "Push note to a linked project (name or path). Requires role: publisher in cross_project_links config."
      },
      "cross_project": {
        "type": "string",
        "description": "Snake_case alias of crossProject."
      }
    },
    "required": [
      "text"
    ]
  },
  "QuickCaptureRequest": {
    "type": "object",
    "properties": {
      "text": {
        "type": "string",
        "description": "Free-form capture text."
      },
      "type": {
        "type": "string",
        "enum": [
          "decision",
          "trap",
          "constraint",
          "note"
        ],
        "description": "Caller-asserted classification. Strongly recommended — the calling agent knows the nature of the capture better than keyword heuristics (cnd_abe61d68: 18 false contradiction positives on a review summary)."
      },
      "context": {
        "type": "string",
        "description": "Optional file/path/scope context to associate with the capture."
      },
      "agent": {
        "type": "string",
        "description": "Agent name."
      },
      "agentId": {
        "type": "string",
        "description": "Registered agent id."
      }
    },
    "required": [
      "text"
    ]
  },
  "CreateSequenceRequest": {
    "type": "object",
    "properties": {
      "name": {
        "type": "string",
        "description": "Sequence name."
      },
      "description": {
        "type": "string",
        "description": "Optional sequence description."
      },
      "status": {
        "type": "string",
        "description": "Status: draft, active, archived."
      },
      "owner": {
        "type": "string",
        "description": "Optional sequence owner."
      },
      "items": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "planId": {
              "type": "string",
              "minLength": 1,
              "description": "Plan item ID referenced by this sequence item."
            },
            "stepId": {
              "type": "string",
              "minLength": 1,
              "description": "Optional plan step ID inside planId for step-level dispatch/readiness."
            },
            "rank": {
              "type": "number",
              "minimum": 1,
              "description": "Positive integer ordering key. Ranks must be unique within a sequence."
            },
            "hard_after": {
              "type": "array",
              "items": {
                "type": "string"
              },
              "description": "Sequence item planId values that must complete before this item becomes ready."
            },
            "soft_after": {
              "type": "array",
              "items": {
                "type": "string"
              },
              "description": "Advisory predecessor planId values; they inform ordering but do not block readiness."
            },
            "lane": {
              "type": "string",
              "description": "Optional lane label used for parallel dispatch grouping and filtering."
            },
            "scope_hint": {
              "type": "string",
              "description": "Optional file/path scope hint for claim and brief generation."
            },
            "rationale": {
              "type": "string",
              "description": "Optional explanation for this item or dependency placement."
            }
          },
          "required": [
            "planId",
            "rank"
          ],
          "additionalProperties": false,
          "description": "Sequence lane item. planId is required; stepId optionally narrows dispatch/readiness to a specific plan step."
        },
        "description": "Sequence items in rank order."
      },
      "tags": {
        "type": "array",
        "items": {
          "type": "string"
        },
        "description": "Optional tags."
      },
      "agent": {
        "type": "string",
        "description": "Agent name."
      },
      "agentId": {
        "type": "string",
        "description": "Registered agent id."
      }
    },
    "required": [
      "name"
    ]
  },
  "UpdateSequenceRequest": {
    "type": "object",
    "properties": {
      "id": {
        "type": "string",
        "description": "Sequence ID or short label."
      },
      "name": {
        "type": "string",
        "description": "Optional new sequence name."
      },
      "description": {
        "type": "string",
        "description": "Optional new description."
      },
      "status": {
        "type": "string",
        "description": "Status: draft, active, archived."
      },
      "owner": {
        "type": "string",
        "description": "Optional sequence owner."
      },
      "items": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "planId": {
              "type": "string",
              "minLength": 1,
              "description": "Plan item ID referenced by this sequence item."
            },
            "stepId": {
              "type": "string",
              "minLength": 1,
              "description": "Optional plan step ID inside planId for step-level dispatch/readiness."
            },
            "rank": {
              "type": "number",
              "minimum": 1,
              "description": "Positive integer ordering key. Ranks must be unique within a sequence."
            },
            "hard_after": {
              "type": "array",
              "items": {
                "type": "string"
              },
              "description": "Sequence item planId values that must complete before this item becomes ready."
            },
            "soft_after": {
              "type": "array",
              "items": {
                "type": "string"
              },
              "description": "Advisory predecessor planId values; they inform ordering but do not block readiness."
            },
            "lane": {
              "type": "string",
              "description": "Optional lane label used for parallel dispatch grouping and filtering."
            },
            "scope_hint": {
              "type": "string",
              "description": "Optional file/path scope hint for claim and brief generation."
            },
            "rationale": {
              "type": "string",
              "description": "Optional explanation for this item or dependency placement."
            }
          },
          "required": [
            "planId",
            "rank"
          ],
          "additionalProperties": false,
          "description": "Sequence lane item. planId is required; stepId optionally narrows dispatch/readiness to a specific plan step."
        },
        "description": "Optional replacement items array."
      },
      "tags": {
        "type": "array",
        "items": {
          "type": "string"
        },
        "description": "Optional replacement tags."
      },
      "agent": {
        "type": "string",
        "description": "Agent name."
      },
      "agentId": {
        "type": "string",
        "description": "Registered agent id."
      }
    },
    "required": [
      "id"
    ]
  },
  "ClaimRequest": {
    "type": "object",
    "properties": {
      "scope": {
        "type": "string",
        "description": "Scope being claimed."
      },
      "description": {
        "type": "string",
        "description": "Description of the work."
      },
      "agent": {
        "type": "string",
        "description": "Agent or person name."
      },
      "agentId": {
        "type": "string",
        "description": "Registered agent id."
      },
      "planId": {
        "type": "string",
        "description": "Optional linked plan item ID."
      },
      "project": {
        "type": "string",
        "description": "Project name or path. Use this when working on a project different from the MCP server workspace (e.g. CLI agents in a different directory)."
      },
      "store": {
        "type": "string",
        "description": "Target store level: local (default), repo, workspace."
      },
      "worktreeBranch": {
        "type": "string",
        "description": "Branch name for the worktree. Defaults to feat/<scope-slug>."
      },
      "worktree": {
        "type": "boolean",
        "description": "Whether to create an isolated git worktree (default true). Pass false for an advisory-only lock with no worktree (trp#431) — for in-place work in the main tree."
      },
      "advisory": {
        "type": "boolean",
        "description": "Alias for worktree:false — advisory-only lock with no worktree (trp#431)."
      },
      "handoffMode": {
        "type": "string",
        "enum": [
          "self-commit",
          "integrator"
        ],
        "description": "Handoff mode: \"self-commit\" (worker commits+merges) or \"integrator\" (another agent reviews+merges). Default: self-commit."
      }
    },
    "required": [
      "scope",
      "description"
    ]
  },
  "ReleaseClaimRequest": {
    "type": "object",
    "properties": {
      "id": {
        "type": "string",
        "description": "Claim ID to release."
      },
      "planStatus": {
        "type": "string",
        "description": "Optional: update linked plan status."
      },
      "coordinator_override": {
        "type": "boolean",
        "description": "Opt-in override for a trusted+ caller releasing a claim they do NOT own (cross-agent teardown, ghost-claim cleanup). Rejected for contributor-level callers; audited when used. trp#928."
      }
    },
    "required": [
      "id"
    ]
  },
  "SessionStartRequest": {
    "type": "object",
    "properties": {
      "agent": {
        "type": "string",
        "description": "Agent name."
      },
      "agentId": {
        "type": "string",
        "description": "Registered agent id."
      },
      "context": {
        "type": "string",
        "description": "Context target path."
      },
      "maintenanceMode": {
        "type": "string",
        "enum": [
          "fast",
          "full"
        ],
        "description": "Maintenance mode. Default is full for explicit session-start calls; use fast to skip non-critical maintenance work."
      },
      "includeContext": {
        "type": "boolean",
        "description": "Include project memory context in the response (equivalent to bclaw_get_context)."
      },
      "includeBoard": {
        "type": "boolean",
        "description": "Include agent board (plans, claims, handoffs) in the response (equivalent to bclaw_get_agent_board)."
      },
      "contextProfile": {
        "type": "string",
        "description": "Context profile when includeContext is true: dev (default), dense, compact, copilot, quick, briefing, openclaw, ops, research. If unset, uses the agent default profile."
      },
      "contextFormat": {
        "type": "string",
        "description": "Context format when includeContext is true: markdown, json, or template."
      }
    }
  },
  "SessionEndRequest": {
    "type": "object",
    "properties": {
      "session": {
        "type": "string",
        "description": "Session ID."
      },
      "agent": {
        "type": "string",
        "description": "Agent name."
      },
      "agentId": {
        "type": "string",
        "description": "Registered agent id."
      },
      "summary": {
        "type": "string",
        "description": "Session summary text."
      },
      "narrative": {
        "type": "string",
        "description": "Free-text narrative of what happened in the session and why. Goes beyond the auto-generated commit list: \"Tried X, failed because Y, pivoted to Z. Watch out for A.\""
      },
      "autoReflect": {
        "type": "boolean",
        "description": "Auto-reflect session notes as candidates."
      },
      "autoRelease": {
        "type": "boolean",
        "description": "Auto-release any active claims at session end."
      },
      "reflectHandoff": {
        "type": "boolean",
        "description": "Materialize an open handoff from git commits since session start."
      },
      "dispatchReview": {
        "type": "boolean",
        "description": "When used with reflectHandoff, auto-dispatch a code review if the reflected handoff is reviewable."
      },
      "reviewer": {
        "type": "string",
        "description": "Explicit reviewer for the reflected handoff review dispatch."
      },
      "reflect": {
        "type": "boolean",
        "description": "Emit the dogfooding reflection prompt (project + your surfaces/skills/tools). Default true — pass false to suppress on a trivial session. Capture actionable findings via bclaw_quick_capture."
      }
    }
  },
  "AddStepRequest": {
    "type": "object",
    "properties": {
      "planId": {
        "type": "string",
        "description": "Plan item ID."
      },
      "data": {
        "type": "object",
        "properties": {
          "text": {
            "type": "string",
            "description": "Step description."
          },
          "title": {
            "type": "string",
            "description": "Alias for text."
          },
          "assignee": {
            "type": "string",
            "description": "Optional assignee."
          },
          "estimated_effort": {
            "type": "number",
            "description": "Step-level estimate in minutes (pln#495). A duration string like \"2h\"/\"30m\" is also accepted and coerced."
          },
          "actual_effort": {
            "type": "string",
            "description": "Step-level actual effort, free-form (\"45m\", \"2h\"), parsed when the estimation report runs."
          }
        },
        "description": "Canonical step payload: { text, title?, assignee? }. title is accepted as an alias for text."
      },
      "text": {
        "type": "string",
        "description": "Legacy top-level step description; prefer data.text."
      },
      "agent": {
        "type": "string",
        "description": "Agent name."
      },
      "agentId": {
        "type": "string",
        "description": "Registered agent id."
      },
      "assignee": {
        "type": "string",
        "description": "Legacy top-level optional assignee; prefer data.assignee."
      },
      "project": {
        "type": "string",
        "description": "Optional: name (or path/basename) of a linked project to add the step in. Defaults to the current project. Same resolution as canonical-grammar tools — accepts cross_project_links and workspace store-chain children."
      }
    },
    "required": [
      "planId"
    ]
  },
  "UpdateStepRequest": {
    "type": "object",
    "properties": {
      "planId": {
        "type": "string",
        "description": "Plan item ID."
      },
      "stepId": {
        "type": "string",
        "description": "Step ID to update."
      },
      "status": {
        "type": "string",
        "description": "New status: todo, in_progress, testing, done, blocked."
      },
      "text": {
        "type": "string",
        "description": "New step text."
      },
      "assignee": {
        "type": "string",
        "description": "New assignee (empty string to unassign)."
      },
      "estimated_effort": {
        "type": "number",
        "description": "Step-level estimate in minutes (pln#495); a duration string is also coerced."
      },
      "actual_effort": {
        "type": "string",
        "description": "Step-level actual effort, free-form (\"45m\", \"2h\")."
      },
      "agent": {
        "type": "string",
        "description": "Agent name."
      },
      "agentId": {
        "type": "string",
        "description": "Registered agent id."
      },
      "project": {
        "type": "string",
        "description": "Optional: name of a linked project to update the step in. Defaults to the current project."
      }
    },
    "required": [
      "planId",
      "stepId"
    ]
  },
  "CompleteStepRequest": {
    "type": "object",
    "properties": {
      "planId": {
        "type": "string",
        "description": "Plan item ID."
      },
      "stepId": {
        "type": "string",
        "description": "Step ID to complete."
      },
      "agent": {
        "type": "string",
        "description": "Agent name."
      },
      "agentId": {
        "type": "string",
        "description": "Registered agent id."
      },
      "project": {
        "type": "string",
        "description": "Optional: name of a linked project to complete the step in. Defaults to the current project."
      }
    },
    "required": [
      "planId",
      "stepId"
    ]
  },
  "DeleteStepRequest": {
    "type": "object",
    "properties": {
      "planId": {
        "type": "string",
        "description": "Plan item ID."
      },
      "stepId": {
        "type": "string",
        "description": "Step ID to delete."
      },
      "agent": {
        "type": "string",
        "description": "Agent name."
      },
      "agentId": {
        "type": "string",
        "description": "Registered agent id."
      },
      "project": {
        "type": "string",
        "description": "Optional: name of a linked project to delete the step from. Defaults to the current project."
      }
    },
    "required": [
      "planId",
      "stepId"
    ]
  }
} as const;
