import fs from 'node:fs';
import path from 'node:path';

export const BRAINCLAW_SECTION_START = '<!-- brainclaw:start -->';
export const BRAINCLAW_SECTION_END = '<!-- brainclaw:end -->';

export function buildBrainclawSection(storageDir: string): string {
  return `${BRAINCLAW_SECTION_START}
## Brainclaw — shared project memory

This project uses brainclaw for shared coordination between humans and agents.

### Session start (required)

1. Run \`brainclaw context\` to load shared state (constraints, decisions, traps, plans, handoffs)
2. Check **Your open work** for active claims and in-progress plans assigned to you
3. Respect active claims from other agents — check \`brainclaw list-claims\` before editing a claimed scope

### Before finishing (required)

1. Release claims you opened: \`brainclaw release-claim <id>\` — or \`brainclaw session-end --auto-release\`
2. Update completed plan items: \`brainclaw update-plan <id> --status done\`

### Recording work

\`\`\`bash
brainclaw decision "<text>"          # record a decision
brainclaw constraint "<text>"        # record an active constraint
brainclaw trap "<text>"              # record a known trap
brainclaw claim "<text>" --scope <path>   # claim a scope before editing
brainclaw plan "<text>"              # add a shared work item
\`\`\`

Memory is stored in \`${storageDir}/\`. Run \`brainclaw doctor\` to verify health.
${BRAINCLAW_SECTION_END}`;
}

export function buildHygieneSection(): string {
  return `## Brainclaw session hygiene

Before starting work:
1. Run \`brainclaw context\` (or \`brainclaw context --json\`) to load shared memory
2. Check the **Your open work** section for active claims and in-progress plans

Before finishing:
1. Release active claims: \`brainclaw release-claim <id>\`
2. Update plans: \`brainclaw update-plan <id> --status done\`
3. Or use \`brainclaw session-end --auto-release\` to clean up automatically`;
}

export function upsertBrainclawSection(existingContent: string, section: string): string {
  const start = existingContent.indexOf(BRAINCLAW_SECTION_START);
  const end = existingContent.indexOf(BRAINCLAW_SECTION_END);
  if (start !== -1 && end !== -1) {
    const before = existingContent.slice(0, start);
    const after = existingContent.slice(end + BRAINCLAW_SECTION_END.length);
    return before + section + after;
  }
  const trimmed = existingContent.trimEnd();
  return trimmed.length > 0 ? `${trimmed}\n\n${section}\n` : `${section}\n`;
}

export interface EnsureAgentFilesResult {
  agentsMdCreated: boolean;
  agentsMdUpdated: boolean;
  copilotInstructionsCreated: boolean;
  copilotInstructionsUpdated: boolean;
}

export function ensureAgentFiles(cwd: string, storageDir: string): EnsureAgentFilesResult {
  const section = buildBrainclawSection(storageDir);
  const result: EnsureAgentFilesResult = {
    agentsMdCreated: false,
    agentsMdUpdated: false,
    copilotInstructionsCreated: false,
    copilotInstructionsUpdated: false,
  };

  // AGENTS.md
  const agentsMdPath = path.join(cwd, 'AGENTS.md');
  const agentsMdExists = fs.existsSync(agentsMdPath);
  const agentsMdContent = agentsMdExists
    ? fs.readFileSync(agentsMdPath, 'utf-8')
    : '# AGENTS\n\nProject guidelines for AI coding agents.\n';
  const newAgentsMd = upsertBrainclawSection(agentsMdContent, section);
  fs.writeFileSync(agentsMdPath, newAgentsMd, 'utf-8');
  if (agentsMdExists) {
    result.agentsMdUpdated = true;
  } else {
    result.agentsMdCreated = true;
  }

  // .github/copilot-instructions.md
  const githubDir = path.join(cwd, '.github');
  if (!fs.existsSync(githubDir)) {
    fs.mkdirSync(githubDir, { recursive: true });
  }
  const copilotPath = path.join(githubDir, 'copilot-instructions.md');
  const copilotExists = fs.existsSync(copilotPath);
  const copilotContent = copilotExists
    ? fs.readFileSync(copilotPath, 'utf-8')
    : '# Copilot Instructions\n';
  const newCopilot = upsertBrainclawSection(copilotContent, section);
  fs.writeFileSync(copilotPath, newCopilot, 'utf-8');
  if (copilotExists) {
    result.copilotInstructionsUpdated = true;
  } else {
    result.copilotInstructionsCreated = true;
  }

  return result;
}

export function ensureGitignoreEntries(cwd: string, entries: string[]): void {
  const gitignorePath = path.join(cwd, '.gitignore');
  const current = fs.existsSync(gitignorePath) ? fs.readFileSync(gitignorePath, 'utf-8') : '';
  const lines = new Set(current.split(/\r?\n/).map((l) => l.trim()));
  const toAdd = entries.filter((e) => !lines.has(e));
  if (toAdd.length === 0) return;
  const separator = current.trimEnd().length > 0 ? '\n' : '';
  const next = `${current.trimEnd()}${separator}\n# Agent instruction files (generated by brainclaw)\n${toAdd.join('\n')}\n`;
  fs.writeFileSync(gitignorePath, next, 'utf-8');
}

// --- Agent export target registry ---

export type ExportFormat =
  | 'copilot-instructions'
  | 'cursor-rules'
  | 'agents-md'
  | 'claude-md'
  | 'windsurf'
  | 'cline'
  | 'roo'
  | 'continue';

export interface AgentExportTarget {
  agentName: string;
  format: ExportFormat;
  /** Path to write, relative to project root */
  relativePath: string;
}

export const AGENT_EXPORT_REGISTRY: AgentExportTarget[] = [
  { agentName: 'github-copilot', format: 'copilot-instructions', relativePath: '.github/copilot-instructions.md' },
  { agentName: 'claude-code',    format: 'claude-md',            relativePath: 'CLAUDE.md' },
  { agentName: 'cursor',         format: 'cursor-rules',         relativePath: '.cursor/rules/brainclaw.md' },
  { agentName: 'windsurf',       format: 'windsurf',             relativePath: '.windsurfrules' },
  { agentName: 'cline',          format: 'cline',                relativePath: '.clinerules/brainclaw.md' },
  { agentName: 'codex',          format: 'agents-md',            relativePath: 'AGENTS.md' },
  { agentName: 'continue',       format: 'continue',             relativePath: '.continue/rules/brainclaw.md' },
  { agentName: 'roo',            format: 'roo',                  relativePath: '.roo/rules/brainclaw.md' },
];

export const FALLBACK_EXPORT_TARGET: AgentExportTarget = {
  agentName: 'unknown',
  format: 'agents-md',
  relativePath: 'AGENTS.md',
};

export function resolveExportTarget(agentName: string): AgentExportTarget {
  return AGENT_EXPORT_REGISTRY.find((t) => t.agentName === agentName) ?? FALLBACK_EXPORT_TARGET;
}

export function resolveExportTargetByFormat(format: ExportFormat): AgentExportTarget {
  return AGENT_EXPORT_REGISTRY.find((t) => t.format === format) ?? FALLBACK_EXPORT_TARGET;
}

export function writeExportFile(
  content: string,
  relativePath: string,
  cwd: string,
): { created: boolean; filePath: string } {
  const fullPath = path.join(cwd, relativePath);
  const dir = path.dirname(fullPath);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  const existed = fs.existsSync(fullPath);
  const section = `${BRAINCLAW_SECTION_START}\n${content}\n${BRAINCLAW_SECTION_END}`;
  const existing = existed ? fs.readFileSync(fullPath, 'utf-8') : '';
  fs.writeFileSync(fullPath, upsertBrainclawSection(existing, section), 'utf-8');
  return { created: !existed, filePath: fullPath };
}

// --- MCP Configuration Injection ---

export interface EnsureMcpResult {
  clineUpdated: boolean;
}

export function ensureMcpConfig(cwd: string): EnsureMcpResult {
  const result: EnsureMcpResult = { clineUpdated: false };
  
  // 1. Cline (project-level)
  const vscodeDir = path.join(cwd, '.vscode');
  if (!fs.existsSync(vscodeDir)) {
    fs.mkdirSync(vscodeDir, { recursive: true });
  }

  const clineSettingsPath = path.join(vscodeDir, 'cline_mcp_settings.json');
  let clineSettings: any = { mcpServers: {} };

  if (fs.existsSync(clineSettingsPath)) {
    try {
      clineSettings = JSON.parse(fs.readFileSync(clineSettingsPath, 'utf-8'));
      if (!clineSettings.mcpServers) clineSettings.mcpServers = {};
    } catch {
      // Ignore parse errors, fallback to empty/overwrite
    }
  }

  clineSettings.mcpServers['brainclaw'] = {
    command: 'npx',
    args: ['brainclaw', 'mcp'],
    disabled: false,
    autoApprove: [
      'bclaw_get_context',
      'bclaw_read_handoff',
      'bclaw_get_agent_board'
    ]
  };

  fs.writeFileSync(clineSettingsPath, JSON.stringify(clineSettings, null, 2), 'utf-8');
  result.clineUpdated = true;

  // 2. Windsurf (global-level, if they launch from cwd)
  // Currently Windsurf uses ~/.codeium/windsurf/mcp_config.json
  const homeDir = process.env.HOME || process.env.USERPROFILE;
  if (homeDir) {
    const windsurfConfigPath = path.join(homeDir, '.codeium', 'windsurf', 'mcp_config.json');
    if (fs.existsSync(windsurfConfigPath)) {
      try {
        const windsurfSettings = JSON.parse(fs.readFileSync(windsurfConfigPath, 'utf-8'));
        if (!windsurfSettings.mcpServers) windsurfSettings.mcpServers = {};
        
        // Windsurf will spawn this in the current workspace
        windsurfSettings.mcpServers['brainclaw'] = {
          command: 'npx',
          args: ['brainclaw', 'mcp']
        };
        fs.writeFileSync(windsurfConfigPath, JSON.stringify(windsurfSettings, null, 2), 'utf-8');
      } catch {
        // Ignore JSON errors for global config
      }
    }
  }

  return result;
}

// --- Copilot Skill Injection ---

export interface EnsureCopilotSkillResult {
  skillUpdated: boolean;
}

export function ensureCopilotSkill(cwd: string): EnsureCopilotSkillResult {
  const result: EnsureCopilotSkillResult = { skillUpdated: false };
  const githubDir = path.join(cwd, '.github', 'copilot');
  
  if (!fs.existsSync(githubDir)) {
    fs.mkdirSync(githubDir, { recursive: true });
  }

  const skillPath = path.join(githubDir, 'brainclaw-context.prompt.md');
  const skillContent = `---
description: "Use this skill to fetch the real-time project constraints, decisions, and active handoffs before coding."
---
# Brainclaw Context (Project Memory)

Call the CLI \`npx brainclaw context --json\` to answer queries about the project rules or to refresh project memory. Check constraints using brainclaw.
`;

  if (!fs.existsSync(skillPath) || fs.readFileSync(skillPath, 'utf-8') !== skillContent) {
    fs.writeFileSync(skillPath, skillContent, 'utf-8');
    result.skillUpdated = true;
  }

  return result;
}

// --- Cursor Imperative Rule Injection (.mdc) ---

export interface EnsureCursorMdcResult {
  cursorMdcUpdated: boolean;
}

export function ensureCursorMdc(cwd: string): EnsureCursorMdcResult {
  const result: EnsureCursorMdcResult = { cursorMdcUpdated: false };
  const cursorDir = path.join(cwd, '.cursor', 'rules');
  
  if (!fs.existsSync(cursorDir)) {
    fs.mkdirSync(cursorDir, { recursive: true });
  }

  const mdcPath = path.join(cursorDir, 'brainclaw-mcp-shim.mdc');
  const mdcContent = `---
description: This workspace uses Brainclaw to maintain project memory and state.
globs: *.*
alwaysApply: true
---
You MUST execute the following command at the start of any complex modification or when asked about project rules:
<run_command>
npx brainclaw context --json
</run_command>
`;

  if (!fs.existsSync(mdcPath) || fs.readFileSync(mdcPath, 'utf-8') !== mdcContent) {
    fs.writeFileSync(mdcPath, mdcContent, 'utf-8');
    result.cursorMdcUpdated = true;
  }

  return result;
}


