import fs from 'node:fs';
import path from 'node:path';

export const BRAINCLAW_SECTION_START = '<!-- brainclaw:start -->';
export const BRAINCLAW_SECTION_END = '<!-- brainclaw:end -->';

export function buildBrainclawSection(storageDir: string): string {
  return `${BRAINCLAW_SECTION_START}
## Shared project memory (brainclaw)

Before working on this project, read the shared memory context:

\`\`\`bash
brainclaw context --json
brainclaw agent-board
\`\`\`

This gives you active constraints, recent decisions, known traps, in-progress plans,
and the latest session handoff.

Memory is stored in \`${storageDir}/\`. Run \`brainclaw doctor\` to verify health.
${BRAINCLAW_SECTION_END}`;
}

export function upsertBrainclawSection(existingContent: string, section: string): string {
  const start = existingContent.indexOf(BRAINCLAW_SECTION_START);
  const end = existingContent.indexOf(BRAINCLAW_SECTION_END);
  if (start !== -1 && end !== -1) {
    const before = existingContent.slice(0, start);
    const after = existingContent.slice(end + BRAINCLAW_SECTION_END.length);
    return before + section + after;
  }
  const trimmed = existingContent.trimEnd();
  return trimmed.length > 0 ? `${trimmed}\n\n${section}\n` : `${section}\n`;
}

export interface EnsureAgentFilesResult {
  agentsMdCreated: boolean;
  agentsMdUpdated: boolean;
  copilotInstructionsCreated: boolean;
  copilotInstructionsUpdated: boolean;
}

export function ensureAgentFiles(cwd: string, storageDir: string): EnsureAgentFilesResult {
  const section = buildBrainclawSection(storageDir);
  const result: EnsureAgentFilesResult = {
    agentsMdCreated: false,
    agentsMdUpdated: false,
    copilotInstructionsCreated: false,
    copilotInstructionsUpdated: false,
  };

  // AGENTS.md
  const agentsMdPath = path.join(cwd, 'AGENTS.md');
  const agentsMdExists = fs.existsSync(agentsMdPath);
  const agentsMdContent = agentsMdExists
    ? fs.readFileSync(agentsMdPath, 'utf-8')
    : '# AGENTS\n\nProject guidelines for AI coding agents.\n';
  const newAgentsMd = upsertBrainclawSection(agentsMdContent, section);
  fs.writeFileSync(agentsMdPath, newAgentsMd, 'utf-8');
  if (agentsMdExists) {
    result.agentsMdUpdated = true;
  } else {
    result.agentsMdCreated = true;
  }

  // .github/copilot-instructions.md
  const githubDir = path.join(cwd, '.github');
  if (!fs.existsSync(githubDir)) {
    fs.mkdirSync(githubDir, { recursive: true });
  }
  const copilotPath = path.join(githubDir, 'copilot-instructions.md');
  const copilotExists = fs.existsSync(copilotPath);
  const copilotContent = copilotExists
    ? fs.readFileSync(copilotPath, 'utf-8')
    : '# Copilot Instructions\n';
  const newCopilot = upsertBrainclawSection(copilotContent, section);
  fs.writeFileSync(copilotPath, newCopilot, 'utf-8');
  if (copilotExists) {
    result.copilotInstructionsUpdated = true;
  } else {
    result.copilotInstructionsCreated = true;
  }

  return result;
}

export function ensureGitignoreEntries(cwd: string, entries: string[]): void {
  const gitignorePath = path.join(cwd, '.gitignore');
  const current = fs.existsSync(gitignorePath) ? fs.readFileSync(gitignorePath, 'utf-8') : '';
  const lines = new Set(current.split(/\r?\n/).map((l) => l.trim()));
  const toAdd = entries.filter((e) => !lines.has(e));
  if (toAdd.length === 0) return;
  const separator = current.trimEnd().length > 0 ? '\n' : '';
  const next = `${current.trimEnd()}${separator}\n# Agent instruction files (generated by brainclaw)\n${toAdd.join('\n')}\n`;
  fs.writeFileSync(gitignorePath, next, 'utf-8');
}
