/**
 * Generates brainclaw-guard wrapper scripts (bash + PowerShell) that intercept
 * npm/pip install commands and check packages via brainclaw check-security.
 */

export function generateBashGuard(brainclawBin: string): string {
  return `#!/usr/bin/env bash
# brainclaw-guard — preinstall security gate
# Generated by: brainclaw setup --security
# Do not edit manually — regenerate with brainclaw setup --security

BRAINCLAW_BIN="${brainclawBin}"
ORIGINAL_CMD="\${BRAINCLAW_GUARD_ORIGINAL_CMD:-npm}"

is_install_command() {
  for arg in "$@"; do
    case "$arg" in
      install|add|i) return 0 ;;
      -*)            continue  ;;
      *)             break     ;;
    esac
  done
  return 1
}

extract_packages() {
  local packages=""
  local skip_next=false
  local past_command=false
  for arg in "$@"; do
    if [ "$skip_next" = true ]; then
      skip_next=false
      continue
    fi
    case "$arg" in
      install|add|i)
        past_command=true
        continue
        ;;
      --save-dev|--save-peer|--save-optional|-D|-P|-O|-g|--global)
        continue
        ;;
      --registry|--prefix)
        skip_next=true
        continue
        ;;
      -*)
        continue
        ;;
      *)
        if [ "$past_command" = true ]; then
          if [ -n "$packages" ]; then
            packages="$packages,$arg"
          else
            packages="$arg"
          fi
        fi
        ;;
    esac
  done
  echo "$packages"
}

# Main logic
if is_install_command "$@"; then
  packages=$(extract_packages "$@")
  if [ -n "$packages" ]; then
    ecosystem="npm"
    if [ "$ORIGINAL_CMD" = "pip" ] || [ "$ORIGINAL_CMD" = "pip3" ]; then
      ecosystem="pypi"
    fi

    result=$("$BRAINCLAW_BIN" check-security --packages "$packages" --ecosystem "$ecosystem" --json 2>/dev/null)
    exit_code=$?

    if [ $exit_code -eq 2 ]; then
      echo "[brainclaw-guard] BLOCKED — supply chain risk detected" >&2
      echo "[brainclaw-guard] Run: brainclaw check-security --packages \\"$packages\\" for details" >&2
      exit 1
    elif [ $exit_code -eq 1 ]; then
      echo "[brainclaw-guard] WARNING — potential supply chain risk" >&2
      echo "[brainclaw-guard] Run: brainclaw check-security --packages \\"$packages\\" for details" >&2
    fi
    # exit_code 0 = pass, continue silently
  fi
fi

exec "$ORIGINAL_CMD" "$@"
`;
}

export function generatePowerShellGuard(brainclawBin: string): string {
  return `# brainclaw-guard — preinstall security gate (PowerShell)
# Generated by: brainclaw setup --security
# Do not edit manually — regenerate with brainclaw setup --security

param([Parameter(ValueFromRemainingArguments)]$Args)

$BrainclawBin = "${brainclawBin}"
$OriginalCmd = if ($env:BRAINCLAW_GUARD_ORIGINAL_CMD) { $env:BRAINCLAW_GUARD_ORIGINAL_CMD } else { "npm" }

function Is-InstallCommand($arguments) {
    foreach ($arg in $arguments) {
        if ($arg -match "^(install|add|i)$") { return $true }
        if ($arg -notmatch "^-") { break }
    }
    return $false
}

function Extract-Packages($arguments) {
    $packages = @()
    $pastCommand = $false
    $skipNext = $false
    foreach ($arg in $arguments) {
        if ($skipNext) { $skipNext = $false; continue }
        if ($arg -match "^(install|add|i)$") { $pastCommand = $true; continue }
        if ($arg -match "^--(registry|prefix)$") { $skipNext = $true; continue }
        if ($arg -match "^-") { continue }
        if ($pastCommand) { $packages += $arg }
    }
    return ($packages -join ",")
}

if (Is-InstallCommand $Args) {
    $packages = Extract-Packages $Args
    if ($packages) {
        $ecosystem = "npm"
        if ($OriginalCmd -match "^pip") { $ecosystem = "pypi" }

        try {
            & $BrainclawBin check-security --packages $packages --ecosystem $ecosystem --json 2>$null | Out-Null
            $exitCode = $LASTEXITCODE
        } catch {
            $exitCode = 0
        }

        if ($exitCode -eq 2) {
            Write-Error "[brainclaw-guard] BLOCKED - supply chain risk detected"
            Write-Error "[brainclaw-guard] Run: brainclaw check-security --packages \`"$packages\`" for details"
            exit 1
        } elseif ($exitCode -eq 1) {
            Write-Warning "[brainclaw-guard] WARNING - potential supply chain risk"
            Write-Warning "[brainclaw-guard] Run: brainclaw check-security --packages \`"$packages\`" for details"
        }
    }
}

& $OriginalCmd @Args
`;
}

export function generatePipBashGuard(brainclawBin: string): string {
  return generateBashGuard(brainclawBin).replace(
    'ORIGINAL_CMD="${BRAINCLAW_GUARD_ORIGINAL_CMD:-npm}"',
    'ORIGINAL_CMD="${BRAINCLAW_GUARD_ORIGINAL_CMD:-pip}"',
  );
}
