/**
 * Generates brainclaw-guard wrapper scripts (bash + PowerShell) that intercept
 * npm/pip/pnpm/yarn install commands and check packages via
 * brainclaw check-security.
 *
 * Mode is enforced by the CLI's exit code, not the wrapper:
 *   exit 0 — pass (silent)
 *   exit 1 — warn (printed; install continues)
 *   exit 2 — block (printed; install aborted)
 * In advisory mode the CLI never emits exit 2, so the wrapper never aborts.
 * The wrapper therefore stays mode-agnostic — flipping advisory↔enforced is
 * a config change, no regeneration required.
 */

export function generateBashGuard(brainclawBin: string): string {
  return `#!/usr/bin/env bash
# brainclaw-guard — preinstall security gate
# Generated by: brainclaw setup-security
# Do not edit manually — regenerate with brainclaw setup-security

BRAINCLAW_BIN="${brainclawBin}"
ORIGINAL_CMD="\${BRAINCLAW_GUARD_ORIGINAL_CMD:-npm}"

is_install_command() {
  for arg in "$@"; do
    case "$arg" in
      install|add|i)       return 0 ;;
      -*)                  continue  ;;
      *)                   break     ;;
    esac
  done
  return 1
}

is_local_or_url() {
  case "$1" in
    .|..|./*|../*|/*|*:/*|git+*|git@*|*.tgz|*.tar.gz|*.whl) return 0 ;;
  esac
  case "$1" in
    [A-Za-z]:[\\\\/]*) return 0 ;;
  esac
  return 1
}

extract_packages() {
  local packages=""
  local req_file=""
  local skip_next=false
  local past_command=false
  for arg in "$@"; do
    if [ "$skip_next" = true ]; then
      # The flag's value lands here; capture it for -r/--requirement.
      case "$prev_flag" in
        -r|--requirement) req_file="$arg" ;;
      esac
      skip_next=false
      prev_flag=""
      continue
    fi
    case "$arg" in
      install|add|i)
        past_command=true
        continue
        ;;
      --save-dev|--save-peer|--save-optional|--save-exact|--save-prod|-D|-P|-O|-E|-S|-g|--global|--no-save|--user|--upgrade|-U|--break-system-packages|--no-deps|--pre|--force-reinstall|--ignore-installed)
        continue
        ;;
      --registry|--prefix|--tag|--registry-url|--cache|--index-url|--extra-index-url|--find-links|--proxy|--cert|--client-cert|--trusted-host|--target|--root|--python|--platform|--abi|--implementation)
        prev_flag="$arg"
        skip_next=true
        continue
        ;;
      -r|--requirement|-e|--editable|-c|--constraint)
        prev_flag="$arg"
        skip_next=true
        continue
        ;;
      -*)
        continue
        ;;
      *)
        if [ "$past_command" = true ]; then
          if is_local_or_url "$arg"; then
            continue
          fi
          if [ -n "$packages" ]; then
            packages="$packages,$arg"
          else
            packages="$arg"
          fi
        fi
        ;;
    esac
  done
  printf '%s\\t%s' "$packages" "$req_file"
}

# Main logic
if is_install_command "$@"; then
  extracted=$(extract_packages "$@")
  packages="\${extracted%%	*}"
  req_file="\${extracted##*	}"

  if [ -n "$packages" ] || [ -n "$req_file" ]; then
    ecosystem="npm"
    if [ "$ORIGINAL_CMD" = "pip" ] || [ "$ORIGINAL_CMD" = "pip3" ]; then
      ecosystem="pypi"
    fi

    args=(check-security --ecosystem "$ecosystem" --json)
    if [ -n "$packages" ]; then args+=(--packages "$packages"); fi
    if [ -n "$req_file" ]; then args+=(--requirements "$req_file"); fi

    "$BRAINCLAW_BIN" "\${args[@]}" >/dev/null 2>&1
    exit_code=$?

    if [ $exit_code -eq 2 ]; then
      echo "[brainclaw-guard] BLOCKED — supply chain risk detected (enforced mode)" >&2
      details_pkgs="\${packages:-$req_file}"
      echo "[brainclaw-guard] Details: $BRAINCLAW_BIN check-security --ecosystem $ecosystem --packages \\"$details_pkgs\\"" >&2
      exit 1
    elif [ $exit_code -eq 1 ]; then
      echo "[brainclaw-guard] WARNING — potential supply chain risk (advisory or warn-threshold verdict)" >&2
      details_pkgs="\${packages:-$req_file}"
      echo "[brainclaw-guard] Details: $BRAINCLAW_BIN check-security --ecosystem $ecosystem --packages \\"$details_pkgs\\"" >&2
    fi
    # exit_code 0 = pass, continue silently
  fi
fi

exec "$ORIGINAL_CMD" "$@"
`;
}

export function generatePowerShellGuard(brainclawBin: string): string {
  return `# brainclaw-guard — preinstall security gate (PowerShell)
# Generated by: brainclaw setup-security
# Do not edit manually — regenerate with brainclaw setup-security

param([Parameter(ValueFromRemainingArguments)]$Args)

$BrainclawBin = "${brainclawBin}"
$OriginalCmd = if ($env:BRAINCLAW_GUARD_ORIGINAL_CMD) { $env:BRAINCLAW_GUARD_ORIGINAL_CMD } else { "npm" }

function Is-InstallCommand($arguments) {
    foreach ($arg in $arguments) {
        if ($arg -match "^(install|add|i)$") { return $true }
        if ($arg -notmatch "^-") { break }
    }
    return $false
}

function Is-LocalOrUrl($arg) {
    if ($arg -eq "." -or $arg -eq "..") { return $true }
    if ($arg -match "^(\\./|\\.\\./|/)") { return $true }
    if ($arg -match "^[A-Za-z]:[\\\\/]") { return $true }
    if ($arg -match "^[a-z]+://") { return $true }
    if ($arg -match "^(git\\+|git@)") { return $true }
    if ($arg -match "\\.(tgz|tar\\.gz|whl)$") { return $true }
    return $false
}

function Extract-Packages($arguments) {
    $packages = @()
    $reqFile = ""
    $pastCommand = $false
    $skipNext = $false
    $prevFlag = ""
    foreach ($arg in $arguments) {
        if ($skipNext) {
            if ($prevFlag -match "^(-r|--requirement)$") { $reqFile = $arg }
            $skipNext = $false
            $prevFlag = ""
            continue
        }
        if ($arg -match "^(install|add|i)$") { $pastCommand = $true; continue }
        if ($arg -match "^(--save-dev|--save-peer|--save-optional|--save-exact|--save-prod|-D|-P|-O|-E|-S|-g|--global|--no-save|--user|--upgrade|-U|--break-system-packages|--no-deps|--pre|--force-reinstall|--ignore-installed)$") { continue }
        if ($arg -match "^(--registry|--prefix|--tag|--registry-url|--cache|--index-url|--extra-index-url|--find-links|--proxy|--cert|--client-cert|--trusted-host|--target|--root|--python|--platform|--abi|--implementation)$") {
            $prevFlag = $arg; $skipNext = $true; continue
        }
        if ($arg -match "^(-r|--requirement|-e|--editable|-c|--constraint)$") {
            $prevFlag = $arg; $skipNext = $true; continue
        }
        if ($arg -match "^-") { continue }
        if ($pastCommand) {
            if (Is-LocalOrUrl $arg) { continue }
            $packages += $arg
        }
    }
    return [PSCustomObject]@{ Packages = ($packages -join ","); RequirementsFile = $reqFile }
}

if (Is-InstallCommand $Args) {
    $extracted = Extract-Packages $Args
    $packages = $extracted.Packages
    $reqFile = $extracted.RequirementsFile

    if ($packages -or $reqFile) {
        $ecosystem = "npm"
        if ($OriginalCmd -match "^pip") { $ecosystem = "pypi" }

        $cliArgs = @("check-security", "--ecosystem", $ecosystem, "--json")
        if ($packages) { $cliArgs += @("--packages", $packages) }
        if ($reqFile) { $cliArgs += @("--requirements", $reqFile) }

        try {
            & $BrainclawBin @cliArgs *> $null
            $exitCode = $LASTEXITCODE
        } catch {
            $exitCode = 0
        }

        $detailsPkgs = if ($packages) { $packages } else { $reqFile }
        if ($exitCode -eq 2) {
            Write-Error "[brainclaw-guard] BLOCKED - supply chain risk detected (enforced mode)"
            Write-Error "[brainclaw-guard] Details: $BrainclawBin check-security --ecosystem $ecosystem --packages \`"$detailsPkgs\`""
            exit 1
        } elseif ($exitCode -eq 1) {
            Write-Warning "[brainclaw-guard] WARNING - potential supply chain risk (advisory or warn-threshold verdict)"
            Write-Warning "[brainclaw-guard] Details: $BrainclawBin check-security --ecosystem $ecosystem --packages \`"$detailsPkgs\`""
        }
    }
}

& $OriginalCmd @Args
exit $LASTEXITCODE
`;
}

export function generatePipBashGuard(brainclawBin: string): string {
  return generateBashGuard(brainclawBin).replace(
    'ORIGINAL_CMD="${BRAINCLAW_GUARD_ORIGINAL_CMD:-npm}"',
    'ORIGINAL_CMD="${BRAINCLAW_GUARD_ORIGINAL_CMD:-pip}"',
  );
}
