/**
 * Regression: ensureCodexMcpConfig must be idempotent and must never advertise
 * tools removed at the v1.0 cut (pln#397 post-alignment audit).
 *
 * Bug observed in the wild:
 *   - the MACHINE-MANAGED header comment block above the tool sections
 *     accumulated (three back-to-back copies), because replaceTomlSection
 *     only replaces `[section]` headers — decorative `# ===` comments were
 *     preserved across runs.
 *   - MCP_HEADLESS_AUTO_TOOL_NAMES is derived from ALL_TOOLS (not the
 *     published catalog), so v1.0-removed tools like `bclaw_get_context`,
 *     `bclaw_list_plans`, `bclaw_create_candidate` etc. kept appearing in
 *     the Codex config even though the tools/list response no longer
 *     surfaces them.
 */
import { afterEach, beforeEach, describe, it } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { ensureCodexMcpConfig } from '../../src/core/agent-files.js';
import { REMOVED_IN_V1_TOOLS } from '../../src/commands/mcp.js';

describe('ensureCodexMcpConfig — idempotency + v1.0 legacy filter', () => {
  let codexHome: string;

  beforeEach(() => {
    codexHome = fs.mkdtempSync(path.join(os.tmpdir(), 'bclaw-codex-config-'));
  });

  afterEach(() => {
    fs.rmSync(codexHome, { recursive: true, force: true });
  });

  it('three successive calls produce one MACHINE-MANAGED header block, not three', () => {
    ensureCodexMcpConfig(undefined, { CODEX_HOME: codexHome } as NodeJS.ProcessEnv);
    ensureCodexMcpConfig(undefined, { CODEX_HOME: codexHome } as NodeJS.ProcessEnv);
    ensureCodexMcpConfig(undefined, { CODEX_HOME: codexHome } as NodeJS.ProcessEnv);

    const content = fs.readFileSync(path.join(codexHome, 'config.toml'), 'utf-8');
    const headerCount = (content.match(/# MACHINE-MANAGED — DO NOT EDIT/g) ?? []).length;
    assert.equal(
      headerCount,
      1,
      `expected exactly 1 MACHINE-MANAGED header after idempotent re-runs, got ${headerCount}`,
    );
  });

  it('does not advertise tools removed at the v1.0 cut', () => {
    ensureCodexMcpConfig(undefined, { CODEX_HOME: codexHome } as NodeJS.ProcessEnv);

    const content = fs.readFileSync(path.join(codexHome, 'config.toml'), 'utf-8');
    const toolsInConfig = [...content.matchAll(/^\[mcp_servers\.brainclaw\.tools\.([^\]]+)\]/gm)]
      .map((m) => m[1]!);

    const leaked = toolsInConfig.filter((t) => REMOVED_IN_V1_TOOLS.has(t));
    assert.deepEqual(
      leaked,
      [],
      `Codex config must not include v1.0-removed tools; leaked: ${leaked.join(', ')}`,
    );
  });

  it('cleans up pre-existing duplicate headers from a prior buggy install', () => {
    // Simulate the exact corrupted state we saw in production: main brainclaw
    // block + three duplicate MACHINE-MANAGED headers + a few stale tool
    // sections including a v1.0-removed one.
    const corrupted = [
      '[mcp_servers.brainclaw]',
      'command = "node"',
      'args = ["dist/cli.js", "mcp"]',
      '',
      '# ===========================================================',
      '# MACHINE-MANAGED — DO NOT EDIT',
      '# Generated by `brainclaw setup`. Changes will be overwritten',
      '# on the next setup run. Only headless-safe tools are listed.',
      '# Sensitive tools (dispatch, accept, reject, create_plan, etc.)',
      '# are intentionally absent — codex will prompt before using them.',
      '# ===========================================================',
      '# ===========================================================',
      '# MACHINE-MANAGED — DO NOT EDIT',
      '# Generated by `brainclaw setup`. Changes will be overwritten',
      '# on the next setup run. Only headless-safe tools are listed.',
      '# Sensitive tools (dispatch, accept, reject, create_plan, etc.)',
      '# are intentionally absent — codex will prompt before using them.',
      '# ===========================================================',
      '# ===========================================================',
      '# MACHINE-MANAGED — DO NOT EDIT',
      '# Generated by `brainclaw setup`. Changes will be overwritten',
      '# on the next setup run. Only headless-safe tools are listed.',
      '# Sensitive tools (dispatch, accept, reject, create_plan, etc.)',
      '# are intentionally absent — codex will prompt before using them.',
      '# ===========================================================',
      '[mcp_servers.brainclaw.tools.bclaw_get_context]',
      'approval_mode = "approve"',
      '',
      '[mcp_servers.brainclaw.tools.bclaw_list_plans]',
      'approval_mode = "approve"',
      '',
    ].join('\n');
    fs.writeFileSync(path.join(codexHome, 'config.toml'), corrupted, 'utf-8');

    ensureCodexMcpConfig(undefined, { CODEX_HOME: codexHome } as NodeJS.ProcessEnv);

    const fixed = fs.readFileSync(path.join(codexHome, 'config.toml'), 'utf-8');
    const headers = (fixed.match(/# MACHINE-MANAGED — DO NOT EDIT/g) ?? []).length;
    assert.equal(headers, 1, `cleanup pass must collapse 3 headers to 1, got ${headers}`);
    assert.ok(
      !fixed.includes('bclaw_get_context]'),
      'v1.0-removed bclaw_get_context must not survive the rewrite',
    );
    assert.ok(
      !fixed.includes('bclaw_list_plans]'),
      'v1.0-removed bclaw_list_plans must not survive the rewrite',
    );
  });
});
